{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aeternislog.redisHost" . }}
  labels:
    {{- include "aeternislog.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aeternislog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "aeternislog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--appendonly", "yes", "--appendfsync", "always"]
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeternislog.redisHost" . }}
  labels:
    {{- include "aeternislog.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "aeternislog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
