apiVersion: v2
name: aeternislog
description: Tamper-Evident Data Anchoring API (Merkle + Hyperledger Fabric) with MongoDB and Redis
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - blockchain
  - hyperledger-fabric
  - audit
  - compliance
  - tamper-evident
home: https://github.com/RicardoMBregalda/aeternis-log
maintainers:
  - name: Ricardo M. Bregalda
